server:
  port: 8081
  error:
    include-message: always

spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public
  #Conexion a base de datos--info de heroku
  datasource:
    url: jdbc:postgresql:${SERVERDB}:5432/${DB}?socketTimeout=3
    username: ${USERDB}
    password: ${PASSDB}
    driverClassName: org.postgresql.Driver

