server:
  port: 8081
  error:
    include-message: always

spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public
  #Conexion a base de datos--info de heroku
  datasource:
    url: jdbc:postgresql://ec2-54-172-175-251.compute-1.amazonaws.com:5432/d8r7vjecmuh5e4?socketTimeout=3
    username: zlvzzsksvezhjd
    password: 0e17144dda39a1b63619654bbbae19f78fb2a2ef86d6148b0c04d02e351a9596
    driverClassName: org.postgresql.Driver
